### ISSUE TITLE
Offer Stumpwm in your script

### ISSUE THREAD

**Issue by OrionRandD** [adriaandegroot/FreeBSDTools#3]
Hi, great script for building a workstation.
Could you add Stumpwm WM to this script?
https://github.com/stumpwm/stumpwm
https://archive.org/details/TheStumpWMExperience
This WM is really great and I use it in debian and in FreeBSD (in virtualbox).
Have a look and see if you like it...
Thx a lot.
There is also a channel in Freenode IRC server dedicated to it.
#stumpwm
In case you want to chat with some people there.

**Comment by OrionRandD** [comment]
I know that it is not really an issue. But, could not find another place to request it...

**Comment by adriaandegroot** [comment]
This is a fine place to request something like that. Thing is, StumpWM isn't a desktop environment -- unlike the four existing options in the script. Just like I didn't add i3 or twm, I think this script is more for not-all-that-custom setups. Of course, you can use StumpWM with a KDE Plasma desktop on FreeBSD instead of KWin. I don't know if it would work with other DE's.

**Comment by OrionRandD** [comment]
It won't. 
Thx anyway
